lib_site 1/lib_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('library.urls'))
]

lib_site 1/library/urls.py
from django.urls import path
from .views import BooksAvailable, LibHomeView
from . import views
from .models import bookview
app_name = "library"

urlpatterns = [
        path('home/',LibHomeView.as_view(), name='homepage'),
        path('book_form/',views.BookForm_view, name='bookform'),
        path('book_list/',BooksAvailable.as_view(), name='booklist'),
        path('Create_user/',views.new_user_req, name='create_user'),
        path('login/',views.login,name='login'),
        path('loggedout/',views.log_out, name='loggedout'),
        path('home/user_profile', views.user_profile, name='userprofile'),
        path('home/user_profile_display', views.user_profile_display, name='userprofiledisplay'),
        path('book_list/request_book_panel/', views.add_in_books, name='requestpanel'),
]

lib_site 1/library/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.text import slugify
import itertools

# Create your models here.

"""class BookUniqueSlug(models.Model):

    slug = models.SlugField(null=True, unique=True, max_length=250)
    #generates slugs and check for uniqueness of the slug
    def _generate_slug(self):
        max_length = self._meta.get_field('slug').max_length
        value = self.book_name
        slug_candidate = slug_orignal = slugify(value, allow_unicode=True)
        for i in itertools.count(1):
            if bookview.objects.filter(slug=slug_candidate).exists():
                break
            slug_candidate = f'{slug_orignal}-{i}'
        self.slug = slug_candidate

    #this gets invoked when the save is performed.
    def save(self, *args, **kwargs):
        if not self.pk:
            self._generate_slug()
            print("checking pk")
        super().save(*args, **kwargs)"""

class bookview(models.Model):
    book_name = models.CharField(max_length=100)
    author_name = models.CharField(max_length=100)
    is_issueable = models.BooleanField(default=False)
    quantity = models.IntegerField(default=1)
    slug = models.SlugField(null=True, unique=True, blank=True)

    def __str__(self):
        return f"{self.book_name} made by {self.author_name}"

    def get_absolute_url(self):
       return reverse("library:BookForm_view.as_view()", kwargs={"slug": self.slug})
    
    def _generate_slug(self):
        max_length = self._meta.get_field('slug').max_length
        value = self.book_name
        slug_candidate = slug_orignal = slugify(value, allow_unicode=True)
        for i in itertools.count(1):
            print(i)
            if bookview.objects.filter(slug=slug_candidate).exists():
                break
            else:
                slug_candidate = f'{slug_orignal}-{i}'
                break
        self.slug = slug_candidate

    #this gets invoked when the save is performed. this is somehow not working
    def save(self, *args, **kwargs):
        #the if logic is just too different that i cannot wrap my head around.
        if self.pk is None:
           # print("checking pk")
            self._generate_slug()
        super(bookview, self).save(*args, **kwargs)
    

    
"""
class LibUserCreation(models.Model):
    username = models.CharField(max_length=20)
    email = models.EmailField(unique=True)
    password1 = models.CharField(max_length=100)
    password2 = models.CharField(max_length=100)
"""
#made userprofile
class UserProfile(models.Model):
    #pk_val_user = models.OneToOneField(get_user_model(), to_field="pk", unique=True, on_delete=models.CASCADE)
    usr_name = models.ForeignKey(get_user_model(), null=True, related_name="%(app_label)s_%(class)s_related", on_delete=models.CASCADE)
    #we don't need this because we can even so show it in the front end by using User.get_email()
    # email_of_user = models.OneToOneField(get_user_model(),to_field='email', unique=True,null=True, on_delete=models.CASCADE)
    address = models.TextField(max_length=250, blank=True)

    def __str__(self):
        return f"{self.usr_name.username} has address {self.address}"

    def check_pk(self):
        if self.pk is None:
            return True
        return False

    def address_of_user(self, pk_id):
        address = UserProfile.objects.get(pk = pk_id)
        return str(address.address)

    def usrname(self):
        """this should give us username field from the usr_name"""
        return self.usr_name.username
    
class ExtUser(User):
         
        def get_email(self, user):
            """Returns the email id this was custom added by me."""
            user_instance = User.objects.get(username=user)
            email = user_instance.email
            return email

        def get_pk_id(self, user):
            """Returns pk id of the user, function made manually"""
            user_instance = User.objects.get(username = user)
            pk_id = user_instance.pk
            return pk_id 



#orders list all
class UsrBookReqOrdersLogs(models.Model):
    user = models.ForeignKey(get_user_model(), null=True, on_delete=models.CASCADE)# input request.user.username here
    #models.ForeignKey( RequestBook,to_field='issue_status', related_name="%(app_label)s_%(class)s_related",on_delete=models.CASCADE)

#specific orders done by user
class RequestBook(models.Model):
    book_req = models.BooleanField(default=False)
    #have to make a foriegn key to associate with user table
    user_details = models.ForeignKey(to=UsrBookReqOrdersLogs, null=True, on_delete=models.CASCADE)
    bookname = models.CharField(max_length=100, default=None)
    author = models.CharField(max_length=100, default=None) 
    issue_status = models.BooleanField(default=True)
    date_time = models.DateTimeField( auto_now_add=True, null=True)

lib_site 1/library/forms.py
from django import forms


#   class bookview(forms.Form):
#   book_name = forms.CharField(max_length=50)
#   author_name = forms.CharField(max_length=50)
#   is_issueable = forms.BooleanField()



   

lib_site 1/library/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import TemplateView, CreateView, ListView, View, FormView
from .models import ExtUser, UserProfile, UsrBookReqOrdersLogs, bookview, RequestBook
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as log
from django.contrib.auth.decorators import login_required
# Create your views here.

class LibHomeView(TemplateView):
    template_name = 'library/home.html'

def BookForm_view(request):
    """i changed it because the slug generation wasnot taking place."""
    #model = bookview
    #fields = ['book_name','author_name', 'is_issueable', 'quantity']
    #success_url = "/book_list/"
    
    if request.method == "POST":

        

        book_name = request.POST.get("book_name")
        author_name = request.POST.get("author_name")
        is_issueable = request.POST.get("is_issueable")
        quantity = request.POST.get("quantity")
        print(request.POST)
        #condition = str(bookview.objects.get(book_name))
        #book = book_name.lower()
        #validations for the form
        book = str(book_name)
        Author = str(author_name)
        
        if  bookview.objects.filter(book_name=book_name).exists():
            messages.info(request, "This book already exists")
            book_name = None
            print("filter block exe")
            return render(request, 'library/bookview_form.html')

        if author_name == "None":
            messages.info(request, "please enter author name")
            print("authornone")
            return render(request, 'library/bookview_form.html')
        if book_name == "None":
            print("booknone")
            messages.info(request, "please enter book name.")
            return render(request, 'library/bookview_form.html')

        
        bk = bookview.objects.create(book_name=book_name, author_name=author_name, is_issueable=is_issueable,quantity=quantity)
        bookview.save(self=bk)
        return redirect(reverse("library:booklist"))
    return render(request, 'library/bookview_form.html')   
        

"""need to create the request book page avaliable so that the post request could be send into the page."""



class BooksAvailable(ListView):
    model = bookview
    template_name = 'library/bookavailable_list.html'
    context_object_name = "book_objects"

#requesting books

#    def Book_Request(request):
 #       Rq = RequestBook()
  #      if request.method == 'POST':
   #         send_req = request.POST.get('book_req')
    #        Rq.objects.create(book_rq = send_req)
     #   return render(request, 'library/request_book_panel.html')


def user_profile(request):
    user = request.user.username
    check2 = User.objects.get(username=user)
    id = check2.pk
    check_ad = UserProfile.objects.get(pk = id)
    address = check_ad.address

    if request.method == "POST":
        #email can't be changed because it should be unique throughout.
        email = request.POST.get("email")
        address = request.POST.get("Address")
        user = request.user.username
        print(email,address)
        #static variables from the backend
        #add_check_var = UserProfile.usrname() 
        id_to_search = ExtUser.get_pk_id(ExtUser, user)
        orignal_email = ExtUser.get_email(ExtUser, user)
        #actual_id = id_to_search.pk
        #how do you find the field id from the user model.
        check_add = UserProfile.objects.get(pk = id_to_search)
        try:
            

            #validations
            if email == None or orignal_email == email:
                ob = User.objects.get(username=user)
                email = ob.email

                       
                if address == None or UserProfile.objects.filter(address=address).exists():
                    print(email,address, "1")
                    messages.info(request, "no changes to be made")
                    return render(request, 'library/user_profile_display.html', context={"address":address,"email":orignal_email})

                elif UserProfile.check_pk is True:
                    print(email,address, "2")
                    up = UserProfile.objects.create(address=address)
                    UserProfile.save(self=up)
                    return render(request, 'library/user_profile_display.html', context={"address":address,"email":orignal_email})

                elif check_add.address is not address:
                    print(email,address, "3")
                    #now this checks if its a new address or not
                    check_add.address = address
                    UserProfile.save(self=check_add)
                    return render(request, 'library/user_profile_display.html', context={"address":address,"email":orignal_email})
            else:
                ob = User.objects.get(username=user)
                ob.email = email
                User.save(self=ob)
                print(email,address)

                if address == None or UserProfile.objects.filter(address=address).exists():
                    print(email,address, "4")
                    messages.info(request, "no changes made.")
                    return render(request, 'library/user_profile_display.html', context={"address":address, "email":orignal_email})

                elif UserProfile.check_pk is True:
                    print(email,address, "5")
                    up = UserProfile.objects.create(address=address)
                    UserProfile.save(self=up)
                    return render(request, 'library/user_profile_display.html', context={"address":address, "email":orignal_email})

                elif check_add.address is not address:
                    print(email,address, "6")
                    #now this checks if its a new address or not
                    check_add.address = address
                    UserProfile.save(self=check_add)
                    return render(request, 'library/user_profile_display.html', context={"address":address, "email":orignal_email})

                return render(request, 'library/user_profile_display.html', context={"address":address, "email":orignal_email})

        
        except:
            print(email,address, "7")
            messages.info(request, "Email entered is already in use")
            return render(request, 'library/user_profile.html')



    return render(request, 'library/user_profile.html', context={"address":address})

def user_profile_display(request):
    """user profile display"""
    user = request.user.username
    id_to_search = ExtUser.get_pk_id(ExtUser, user)
    orignal_email = ExtUser.get_email(ExtUser, user)
    address = UserProfile.address_of_user(UserProfile, id_to_search)
    return render(request, 'library/user_profile_display.html', context={"address":address, "email":orignal_email})

"""need to make a cart page where you can see the requested books"""

def new_user_req(request):

    #forms = LibUserCreation()
    User._meta.get_field('email')._unique = True
    if request.method == 'POST':
        Username = request.POST.get('username') 
        Email = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')

        #added email validator
        if Email == None:
            messages.info(request, 'Email is necessary!')
            return render(request, reverse('library:login'))
        
        #added email validator
        if User.objects.filter(email = Email).exists():
            messages.info(request, 'This email already exists.!')
            return render(request, reverse('library:login'))

        if password1 == password2:
                my_user = User.objects.create_user(Username, Email, password1)
                messages.info(request, 'account sucessfully made!')
                return redirect(reverse('library:homepage'))
                
        else:
            messages.info(request,"password don't match")
          
    return render(request,'library/libnewuser_view.html')

def login(request):
    if request.method == 'POST':
       
        Username = request.POST.get('username')
        password = request.POST.get('password1')
        
        user = authenticate(username = Username, password = password)
        if user is not None:
            log(request, user)
            return redirect(reverse('library:homepage'))
        else:
            messages.info(request, 'Bad credentials')
            return redirect(reverse('library:login'))        

    return render(request, 'library/login.html')

def log_out(request):
    logout(request)
    return redirect(reverse('library:login'))

# this is adding in the cart

@login_required
def add_in_books(request):
    #in time when i start using this request then i will have to make a check for address so that they can order
    instance = UsrBookReqOrdersLogs.objects.get(user=user)
    
    if RequestBook.objects.filter(user_details=instance).exists():
        req_table = RequestBook.objects.get(user_details=instance)
    else:
        return render(request, "library/request_book_panel.html", context={"bool":True})

    if request.method == "POST":
        slug = request.POST.get("slug")
        user = request.user.username 
        book = get_object_or_404(bookview, slug=slug)
       # usr_instance = UsrBookReqOrdersLogs.objects.get(user=user)
       
        
        #creation of logs
        try:
            instance = UsrBookReqOrdersLogs.objects.get(user=user)
            create_rq = RequestBook.objects.create(book_req = True, user_details = instance, bookname = book.book_name, author = book.author_name)
            RequestBook.save(self=create_rq)
            req_table = RequestBook.objects.get(user_details=instance)

lib_site 1/library/templates/library/bookavailable_list.html
{% extends "base.html" %}
{% block content %}
<style>
.container{
  padding: 100px;
}
.link{
  height: 368.45px;
  width: 450.38px;
}

</style> 

<div class="container align-content-center fw-semibold">
    </h1>Books Available </h1>
<div>

<div class="row-cols-auto">
    {% for books in book_objects %}
     
    <div class="container row align-items-md-stretch" id='container'>
      <a href="{% url 'library:requestpanel' %}" class='link' value="{{books.slug}}"> <!--my thought process is right now to make a boolean field and take in the user form and then use get request to find the books.book_name and make a foreign key and conenct it to the user.-->
        <form action= "{% url 'library:requestpanel' %}" method='POST'>
          {% csrf_token %}
        <button class="btn btn-outline-dark" type='btn btn-outline-dark' id="slug" value="{{books.slug}}">
        
        <div class="container col-l-5 " >
          <h3>{{books.book_name}}</h3>
          <p>{{books.author_name}}</p>
          {% if books.is_issueable is True %}
            <p>The book is issueable</p>
          {% else %}
            <p>This book is not issueable</p> 
          {% endif %} 
          
       </div> 
      </button>
      <input type="hidden" name="slug" value="{{books.slug}}">
    </form>
    </a>  
    </div>
     
 
    {% endfor %}
  
</div>

{% endblock %}

lib_site 1/library/templates/library/bookview_form.html
{% extends "base.html" %}
{% block content %}

<style>


.container{
  padding: 85px;
}
</style> 
<header class="container-fluid">
<div class="jumbotron jumbotron-fluid">
  <div class="container bg-grey">
    <h1 class="display-3 fw-semibold">Book Form</h1>
    {% if user.is_authenticated %}
    <p class="lead">hello, you can enter book details here. </p>
    {% else %}
    <p>You don't have the permission to enter new book</p>
    {% endif %}
    
    <hr class="my-2">
  </div>
</div>
</header>
{% if user.is_staff == True %}
<div class="container align-content-center fw-semibold">
    </h1>Enter New Book Detail</h1>
<div>
<div class="container">
    <!---implement css form-->
    <div class="row align-items-md-stretch">
      <div class="container col-l-7 " label='form'>
          <form method='POST' class="bg-opacity-100">
            {% csrf_token %}
            <div class="mb-3">
              <label for="book_name" class="form-label">Book Name</label>
              <div id="bookHelp" class="form-text">enter the book name in the field given below.</div>  
              <input type="text" class="form-control" name="book_name" aria-describedby="bookHelp">
            </div>
            <div class="mb-3">
              <label for="author_name" class="form-label">Author Name</label>
              <div id="authorHelp" class="form-text">enter the Author name in field given below</div>  
              <input type="text" class="form-control" name="author_name" aria-describedby="authorHelp">
            </div>
            <div class="mb-3">
            <input type="checkbox" name="is_issueable" id="is_issueable" value="True">
            <label class="form-check-label" for="is_issueable">Is issueable?</label>
            </div>
            <div class="mb-1">
              <input type="number" name="quantity" id="quantity" max=100>
              <label class="form-number-label" for="quantity">quantity</label>
            </div>
            <input type="submit" id="submit" class="btn btn-primary" type="button">
          </form>   
       </div> 
       {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alret-dismissible-fade-show" role="alert">
    <strong>Message:</strong>{{message}}
          <button type='button' class='close' data-dismiss='alert' aria-label='close'>
          <span aria-hidden="true">&times;</span>
          </button>
      </div>
      {% endfor %}  
    </div>
  {% elif user.is_authenticated %}
  <div class="container align-content-center">
    <h2>This side is only for the library mangement!</h2>
    </div>
  {% else %}
  <div class="container align-content-center">
  <h2>Please login for more!</h2>
  </div>
 {% endif %}
</div>

{% endblock content %}

lib_site 1/library/templates/library/home.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<style>
.jumbotron {
  background-image: url({% static 'library/static_lib.png' %});
  background-size: auto;
}
.container{
  padding: 80px;
}
</style> 

<div class="container">
    
     <div class="p-5 mb-4 bg-light rounded-3">
     
      <div class="container-fluid py-5">
      
        <h1 class="display-5 fw-bold">Welcome To The Online Library</h1>
        <p class="col-md-8 fs-4">Login to get access to the books available.</p>
           
      </div>
      
    </div>
    <div class="row align-items-md-stretch">
      <div class="container col-l-7">
        
          <div class="h-100 p-5 text-bg-dark rounded-4">
            <h2>Login into library</h2>
            <p>Login to get access to the books available.</p>
            <a class="btn btn-outline-light" type="button" href="{%url 'library:login'%}">Go to login page</a>
          </div>   
      </div>
      <div class="container col-l-6">
        <div class="h-100 p-5 bg-light border rounded-3">
          <h2>Books Available</h2>
          <p>see what books do we have in store for you to borrow</p>
          <a class="btn btn-outline-secondary" type="button" href="{%url 'library:booklist'%}">Go to Books page</a>
        </div>
      </div>
    </div>
    {% for message in messages %}
		    <div class="alert alert-{{ message.tags }} alret-dismissible-fade-show" role="alert">
			<strong>Message:</strong>{{message}}
            <button type='button' class='close' data-dismiss='alert' aria-label='close'>
            <span aria-hidden="true">&times;</span>
            </button>
		    </div>
		    {% endfor %}

</div>

{% endblock content %}

lib_site 1/library/templates/library/libnewuser_view.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<style>
.container{
  padding: 80px;
}
</style> 

<div class="container">
    
     
    <div class="row align-items-md-stretch">
      <div class="container col-l-7">
        
          <div class="h-100 p-5 text-bg-dark rounded-4">
            <h2 class='fw-light'>Create a new user</h2>
            <p>Login to get access to the books available.</p>
            <form action="/Create_user/" method='POST'>
              {% csrf_token %}

              <div class="mb-3">
              <label for="username" class="form-label">Username</label>
                <input type="text" class="form-control" name="username" aria-describedby="username">
                <div id="username" class="form-text">use a unique name for your account, as this can't be changed once made.</div>
              </div>

              <div class="mb-3">
              <label for="email" class="form-label">Email address</label>
                <input type="email" class="form-control" name="email" aria-describedby="email">
                <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
              </div>

              <div class="mb-3">
                <label for="password1" class="form-label">Password</label>
                  <input type="password" class="form-control" name="password1">
              </div>

              <div class="mb-3">
                <label for="password2" class="form-label">Confirm Password</label>
                  <input type="password" class="form-control" name="password2">
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            <a class='btn btn-outline-light' href='{% url "library:login" %}'>login.</a>
          </div>   
      </div>
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alret-dismissible-fade-show" role="alert">
    <strong>Message:</strong>{{message}}
          <button type='button' class='close' data-dismiss='alert' aria-label='close'>
          <span aria-hidden="true">&times;</span>
          </button>
      </div>
      {% endfor %}

</div>

{% endblock content %}

lib_site 1/library/templates/library/login.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<style>
.container{
  padding: 80px;
}
</style> 

<div class="container">
    
     
    <div class="row align-items-md-stretch">
      <div class="container col-md-7">
        
          <div class="h-100 p-5 text-bg-dark rounded-4">
            {% if user.is_authenticated %}
            <h2 class='fw-light'>hello {{user.get_username}}, you're already logged in!</h2>
            <p>perphas you want to log-out?</p>
            <a href='/loggedout/'><button class='btn btn-outline-light' type="submit">logout</button></a>
            {% else %}
            <h2 class='fw-light'>hello login here</h2>
            <p>Login to get access to the books available.</p>
            <form action='/login/' method='POST'>
            {% csrf_token %}
              <div class="mb-3">
              <label for="username" class="form-label">Username</label>
                <input type="text" class="form-control" name="username" aria-describedby="emailHelp">
                <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
              </div>
              <div class="mb-3">
                <label for="password1" class="form-label">Password</label>
                  <input type="password" class="form-control" name="password1">
              </div>
              <button type="submit" class="btn btn-primary">login</button>
            </form>
            <a class='btn btn-outline-light' href='{% url "library:create_user"%}' padding= '20px'>create new user</a>
          </div>   
          <div class="form-group">
		    {% for message in messages %}
		    <div class="alert alert-{{ message.tags }} alret-dismissible-fade-show" role="alert">
			<strong>Message:</strong>{{message}}
            <button type='button' class='close' data-dismiss='alert' aria-label='close'>
            <span aria-hidden="true">&times;</span>
            </button>
		    </div>
		    {% endfor %}
        {% endif %}
	        </div>
      </div>


</div>

{% endblock content %}

lib_site 1/library/templates/library/request_book_panel.html
{% extends "base.html" %}
{% block content %}
<!---HAVE TO CREATE THIS AS THE CART PAGE-->
<style>
.jumbotron {
  
  background-size: auto;
}
.container{
  padding: 80px;
}

</style> 
{% if bool==True %}

<i class="fas fa-heading    "> YOUR CART IS EMPTY</i>

{% else %}
<div class="container-xxl">

  {% for req in req_book %}
  <a href="#" class="btn btn-primary">
    <div class="card w-100">
      <div class="card-body">
        <h5 class="card-title">{{req.bookname}}</h5>
        <p class="card-text">by {{req.author}}</p>
        <p class="card-text">on {{req.date_time}}</p>
      </div>
    </div>
  </a>
  {% endfor %}
    {% for message in messages %}
		    <div class="alert alert-{{ message.tags }} alret-dismissible-fade-show" role="alert">
			<strong>Message:</strong>{{message}}
            <button type='button' class='close' data-dismiss='alert' aria-label='close'>
            <span aria-hidden="true">&times;</span>
            </button>
		    </div>
		    {% endfor %}

</div>

{% endblock content %}

lib_site 1/library/templates/library/user_profile.html
{% extends "base.html" %}
{% block content %}
<style>
  .container{
    padding: 80px;
  }
  </style>
<body>
    <div class="container align-content-center fw-semi-bold">
    </h1>Hello {{ user.get_username }}</h1>
    <div>
<div class="container">
    <!---implement css form-->
    <div class="row align-items-md-stretch">
      <div class="container col-l-7 " label='form'>
          <form method='POST' class="bg-opacity-100">
            {% csrf_token %}
            <div class="mb-3">
              <label for="email" class="form-label">Email ID</label> 
              <input type="text" class="form-control" name="email" aria-describedby="emailHelp" placeholder="{{ user.get_email }}" initial="None">
            </div>
            <div class="mb-3">
            <label class="form-label" for="Address">Address</label>
            <input class="form-control" type="textarea" name="Address" id="Address" placeholder="{{ address }}" initial="None">
            </div>
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alret-dismissible-fade-show" role="alert">
              <strong>Message:</strong>{{message}}
              <button type='button' class='close' data-dismiss='alert' aria-label='close'>
              <span aria-hidden="true">&times;</span>
              </button>
              </div>
            {% endfor %}
            <input type="submit" id="submit" class="btn btn-primary" type="button">
          </form>   
       </div> 
  </body>
</html>

{% endblock content %}

lib_site 1/library/templates/library/user_profile_display.html
{% extends "base.html" %}
{% block content %}
<style>
    .container{
      padding: 80px;
    }
    </style>

<body>

    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-3">Hello {{ user.get_username }}</h1>
            <p class="lead">your details</p>
            <hr class="my-2">
            <ul class="display-6">
                <li>Email Id: {{ email }}</li>
                <li>Address: {{ address }}</li>
            </ul>
            <p>To add address please click on the edit button.</p>
            <p class="lead">
                <a class="btn btn-primary btn-md" href="{%url 'library:userprofile'%}" role="button">Edit Info</a>
            </p>
        </div>
    </div>
</body>

{% endblock content %}