lib_site 1/lib_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('library.urls'))
]

lib_site 1/library/urls.py
from django.urls import path
from .views import BooksAvailable, LibHomeView
from . import views
from .models import bookview
app_name = "library"

urlpatterns = [
        path('home/',LibHomeView.as_view(), name='homepage'),
        path('book_form/',views.BookForm_view, name='bookform'),
        path('book_list/',BooksAvailable.as_view(), name='booklist'),
        path('Create_user/',views.new_user_req, name='create_user'),
        path('login/',views.login,name='login'),
        path('loggedout/',views.log_out, name='loggedout'),
        path('home/user_profile', views.user_profile, name='userprofile'),
        path('home/user_profile_display', views.user_profile_display, name='userprofiledisplay'),
        path('book_list/request_book_panel/', views.add_in_books, name='requestpanel'),
]

lib_site 1/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>library site</title>
       <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'library:userprofiledisplay' %}">{{user.get_username}}</a>
        {% else %}
        <a class="navbar-brand" href="{% url 'library:homepage' %}">Online Lib</a>
        {% endif %}
        <button class="navbar-toggler hidden-lg-up" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
            aria-expanded="false" aria-label="Toggle navigation">menu</button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0" id="collapsibleNavId">
            <li class="nav-item active">
              <a class="nav-link" href="{%url 'library:homepage'%}">Home </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%url 'library:booklist'%}">Library books</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link" href="{%url 'library:bookform'%}">forms</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link" href="{%url 'library:requestpanel'%}">Your Cart</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
      
  </body>
  <div container="fluid">
  {% block content %}
  
  
  {% endblock content %}
  </div>
  
   <footer class="pt-3 mt-4 text-muted border-top">
            &copy; 2022
        </footer>
</html>